/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/land-cruiser.glb --output src/components/LandCruiser.tsx --types --transform 
Files: public/models/land-cruiser.glb [17.71MB] > C:\Users\Mohammad Hashir\Desktop\FYP_code\car-showcase\src\components\land-cruiser-transformed.glb [1.83MB] (90%)
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2022-toyota-land-cruiser-300-vxr-3dfcd7904cdb4e52afa3ce59fa59e1a5
Title: 2022 Toyota Land Cruiser 300 VX.R
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_021_TMI_Exhaust_030_0: THREE.Mesh
    TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_022_TMI_Cabin_A_008_0: THREE.Mesh
    TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_023_TMI_Cabin_Leather_A_008_0: THREE.Mesh
    TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_024_TMI_Cabin_Grid_B_012_0: THREE.Mesh
    TSM_Body_101_SM_Body_101_MI_Cabin_A_009_TMI_Glass_011_0: THREE.Mesh
    TSM_Body_101_SM_Body_101_MI_Cabin_A_017_TMI_Cabin_Grid_A_003_0: THREE.Mesh
    TSM_Body_101_SM_Body_101_MI_Cabin_A_023_TMI_1350010001_044_0: THREE.Mesh
    TSM_Body_101_SM_Body_101_MI_Cabin_A_024_Mirror_0: THREE.Mesh
    TSM_Body_101_SM_Body_101_MI_Cabin_A_027_TMI_Dashboard_007_0: THREE.Mesh
    TSM_Bumper_F_101_SM_Bumper_F_101_MI_1350010001_008_TMI_Logo_007_0: THREE.Mesh
    TSM_Diffuser_B_101_SM_Diffuser_B_101_MI_1350010001_009_TMI_Light_011_0: THREE.Mesh
    TSM_Engine_101_SM_Engine_101_MI_Engine_A_001_TMI_Engine_Plastic_A1_0: THREE.Mesh
    TSM_Light_B_101_SM_Light_B_101_MI_Light_012_phong1_0: THREE.Mesh
    TSK_Suspension_101_001_SK_Suspension_101_001_MI_Exhaust_040_TMI_Suspension_002_0: THREE.Mesh
    TSK_Suspension_101_001_SK_Suspension_101_001_MI_Exhaust_041_TMI_Suspension_B1_0: THREE.Mesh
    TpolySurface13_TMI_Change_Brake_002_0: THREE.Mesh
    TTpolySurface499_rimMI_ChangeA_Rim_002_0: THREE.Mesh
  }
  materials: {
    TMI_Exhaust_030: THREE.MeshStandardMaterial
    TMI_Cabin_A_008: THREE.MeshStandardMaterial
    TMI_Cabin_Leather_A_008: THREE.MeshStandardMaterial
    TMI_Cabin_Grid_B_012: THREE.MeshPhysicalMaterial
    TMI_Glass_011: THREE.MeshPhysicalMaterial
    TMI_Cabin_Grid_A_003: THREE.MeshStandardMaterial
    TMI_1350010001_044: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    TMI_Dashboard_007: THREE.MeshStandardMaterial
    TMI_Logo_007: THREE.MeshStandardMaterial
    TMI_Light_011: THREE.MeshStandardMaterial
    TMI_Engine_Plastic_A1: THREE.MeshStandardMaterial
    phong1: THREE.MeshPhysicalMaterial
    TMI_Suspension_002: THREE.MeshStandardMaterial
    TMI_Suspension_B1: THREE.MeshStandardMaterial
    TMI_Change_Brake_002: THREE.MeshStandardMaterial
    rimMI_ChangeA_Rim_002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/land-cruiser-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_021_TMI_Exhaust_030_0.geometry} material={materials.TMI_Exhaust_030} scale={0.01} />
      <mesh geometry={nodes.TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_022_TMI_Cabin_A_008_0.geometry} material={materials.TMI_Cabin_A_008} scale={0.01} />
      <mesh geometry={nodes.TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_023_TMI_Cabin_Leather_A_008_0.geometry} material={materials.TMI_Cabin_Leather_A_008} scale={0.01} />
      <mesh geometry={nodes.TSK_Body_Bones_101_001_SK_Body_Bones_101_001_MI_Exhaust_024_TMI_Cabin_Grid_B_012_0.geometry} material={materials.TMI_Cabin_Grid_B_012} scale={0.01} />
      <mesh geometry={nodes.TSM_Body_101_SM_Body_101_MI_Cabin_A_009_TMI_Glass_011_0.geometry} material={materials.TMI_Glass_011} scale={0.01} />
      <mesh geometry={nodes.TSM_Body_101_SM_Body_101_MI_Cabin_A_017_TMI_Cabin_Grid_A_003_0.geometry} material={materials.TMI_Cabin_Grid_A_003} scale={0.01} />
      <mesh geometry={nodes.TSM_Body_101_SM_Body_101_MI_Cabin_A_023_TMI_1350010001_044_0.geometry} material={materials.TMI_1350010001_044} scale={0.01} />
      <mesh geometry={nodes.TSM_Body_101_SM_Body_101_MI_Cabin_A_024_Mirror_0.geometry} material={materials.Mirror} scale={0.01} />
      <mesh geometry={nodes.TSM_Body_101_SM_Body_101_MI_Cabin_A_027_TMI_Dashboard_007_0.geometry} material={materials.TMI_Dashboard_007} scale={0.01} />
      <mesh geometry={nodes.TSM_Bumper_F_101_SM_Bumper_F_101_MI_1350010001_008_TMI_Logo_007_0.geometry} material={materials.TMI_Logo_007} scale={0.01} />
      <mesh geometry={nodes.TSM_Diffuser_B_101_SM_Diffuser_B_101_MI_1350010001_009_TMI_Light_011_0.geometry} material={materials.TMI_Light_011} scale={0.01} />
      <mesh geometry={nodes.TSM_Engine_101_SM_Engine_101_MI_Engine_A_001_TMI_Engine_Plastic_A1_0.geometry} material={materials.TMI_Engine_Plastic_A1} scale={0.01} />
      <mesh geometry={nodes.TSM_Light_B_101_SM_Light_B_101_MI_Light_012_phong1_0.geometry} material={materials.phong1} scale={0.01} />
      <mesh geometry={nodes.TSK_Suspension_101_001_SK_Suspension_101_001_MI_Exhaust_040_TMI_Suspension_002_0.geometry} material={materials.TMI_Suspension_002} scale={0.01} />
      <mesh geometry={nodes.TSK_Suspension_101_001_SK_Suspension_101_001_MI_Exhaust_041_TMI_Suspension_B1_0.geometry} material={materials.TMI_Suspension_B1} scale={0.01} />
      <mesh geometry={nodes.TpolySurface13_TMI_Change_Brake_002_0.geometry} material={materials.TMI_Change_Brake_002} position={[-0.008, 0.004, -0.013]} scale={0.01} />
      <mesh geometry={nodes.TTpolySurface499_rimMI_ChangeA_Rim_002_0.geometry} material={materials.rimMI_ChangeA_Rim_002} position={[-0.008, 0.004, -0.013]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/land-cruiser-transformed.glb')
